spring:
  application:
    name: HabitService
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/habit
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Moscow
  jackson:
    default-property-inclusion: non_null
server:
  port: 8083
